-- Supabase projects created under the opt-in Data API grant model do not
-- automatically expose public tables. Preserve the RLS-governed Data API
-- surface that the production lineage already has for migrations 0001-0021,
-- while keeping the server-adapter tables added in 0022-0024 service-only.
--
-- Every table below has RLS enabled. The service_role remains restricted to
-- trusted server-side adapters; anon/authenticated access is still decided by
-- the table policies rather than by the table grant alone.

-- Legacy RLS-governed Data API surface from migrations 0001-0021.
grant select, insert, update, delete on table
  public.profiles,
  public.organizations,
  public.organization_memberships,
  public.seasons,
  public.teams,
  public.team_memberships,
  public.players,
  public.parent_invites,
  public.player_guardians,
  public.events,
  public.rsvps,
  public.announcements,
  public.media_items,
  public.registration_requests,
  public.snack_schedule_slots,
  public.volunteer_signups,
  public.sponsors,
  public.weather_alerts,
  public.parent_replays,
  public.team_chat_channels,
  public.team_chat_messages,
  public.chat_moderation_audit_events,
  public.notifications,
  public.push_subscriptions,
  public.roster_imports,
  public.roster_import_rows,
  public.audit_events,
  public.guardian_authorizations,
  public.emergency_contacts,
  public.player_health_notes,
  public.notification_preferences,
  public.notification_delivery_attempts,
  public.field_locations,
  public.event_series,
  public.event_change_logs,
  public.field_reservations,
  public.team_chat_threads,
  public.team_chat_message_reads,
  public.team_chat_reactions,
  public.team_chat_attachments,
  public.team_chat_reports,
  public.parent_replay_templates,
  public.ai_generation_runs,
  public.learning_plans,
  public.sponsor_packages,
  public.sponsor_placements,
  public.sponsor_assets,
  public.registration_approval_actions,
  public.mobile_usage_events,
  public.team_logo_assets,
  public.sponsor_billing_records,
  public.team_build_plans,
  public.team_brand_profiles,
  public.team_brand_surface_validation_runs,
  public.brand_asset_uploads,
  public.brand_monitoring_events,
  public.rsvp_change_logs,
  public.support_requests
to anon, authenticated, service_role;

-- Server-adapter-only tables from migrations 0022-0024.
revoke all on table
  public.drill_video_sources,
  public.drill_videos,
  public.drill_video_assignments,
  public.offline_action_receipts,
  public.event_attendance,
  public.coach_event_notes,
  public.conflict_reviews,
  public.parent_replay_engagement,
  public.provider_webhook_events,
  public.volunteer_waitlist_entries,
  public.volunteer_transfer_requests,
  public.player_media_consents,
  public.media_review_history,
  public.organization_stripe_accounts,
  public.fee_definitions,
  public.family_obligations,
  public.payment_evidence,
  public.practice_run_receipts,
  public.family_event_handoffs,
  public.game_day_resolution_reviews
from public, anon, authenticated;

grant select, insert, update, delete on table
  public.drill_video_sources,
  public.drill_videos,
  public.drill_video_assignments,
  public.offline_action_receipts,
  public.event_attendance,
  public.coach_event_notes,
  public.conflict_reviews,
  public.parent_replay_engagement,
  public.provider_webhook_events,
  public.volunteer_waitlist_entries,
  public.volunteer_transfer_requests,
  public.player_media_consents,
  public.media_review_history,
  public.organization_stripe_accounts,
  public.fee_definitions,
  public.family_obligations,
  public.payment_evidence,
  public.practice_run_receipts,
  public.family_event_handoffs,
  public.game_day_resolution_reviews
to service_role;
